# Generated by Django 4.0.3 on 2022-04-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('description', models.CharField(max_length=4000)),
                ('school', models.CharField(max_length=30)),
                ('materials', models.CharField(max_length=100)),
                ('range', models.IntegerField()),
                ('area', models.IntegerField()),
                ('area_shape', models.CharField(blank=True, choices=[('R', 'Radius'), ('C', 'Cube'), ('S', 'Sphere'), ('Y', 'Cylinder'), ('N', 'None')], max_length=20)),
                ('att_save', models.CharField(blank=True, choices=[('M', 'Melee Spell Attack'), ('R', 'Ranged Spell Attack'), ('D', 'Dexterity Save'), ('S', 'Strength Save'), ('C', 'Constitution Save'), ('I', 'Intelligence Save'), ('W', 'Wisdom Save'), ('H', 'Charisma Save'), ('N', 'None')], max_length=20)),
                ('casting_time', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('concentration', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effects', models.ManyToManyField(blank=True, to='app.spell')),
            ],
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.ManyToManyField(blank=True, to='app.spell')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.ManyToManyField(choices=[('V', 'Verbal'), ('S', 'Somatic'), ('M', 'Material')], to='app.spell')),
            ],
        ),
    ]
