# Generated by Django 4.0.3 on 2022-04-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='components',
            field=models.ManyToManyField(blank=True, to='app.spell'),
        ),
    ]
