# Generated by Django 4.0.3 on 2022-04-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_component_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='upcasting',
            field=models.CharField(default='You may not upcast this spell.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='spell',
            name='area_shape',
            field=models.CharField(choices=[('R', 'Radius'), ('C', 'Cube'), ('S', 'Sphere'), ('Y', 'Cylinder'), ('N', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='spell',
            name='att_save',
            field=models.CharField(choices=[('M', 'Melee Spell Attack'), ('R', 'Ranged Spell Attack'), ('D', 'Dexterity Save'), ('S', 'Strength Save'), ('C', 'Constitution Save'), ('I', 'Intelligence Save'), ('W', 'Wisdom Save'), ('H', 'Charisma Save'), ('N', 'None')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='spell',
            name='casting_time',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=models.CharField(default='No description provided.', max_length=4000),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='spell',
            name='materials',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(default='No name', max_length=20),
        ),
        migrations.AlterField(
            model_name='spell',
            name='school',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
