# Generated by Django 4.0.3 on 2022-04-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_school_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=models.TextField(default='No description provided.', max_length=4000),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='spell',
            name='upcasting',
            field=models.TextField(default='You may not upcast this spell.', max_length=1000),
        ),
    ]
