# Generated by Django 4.0.3 on 2022-04-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_spell_area_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='char_class',
            field=models.ManyToManyField(blank=True, to='app.characterclass'),
        ),
        migrations.AddField(
            model_name='spell',
            name='components',
            field=models.ManyToManyField(blank=True, to='app.component'),
        ),
        migrations.AddField(
            model_name='spell',
            name='damage_type',
            field=models.ManyToManyField(blank=True, to='app.damagetype'),
        ),
        migrations.AddField(
            model_name='spell',
            name='effects',
            field=models.ManyToManyField(blank=True, to='app.effect'),
        ),
        migrations.AddField(
            model_name='spell',
            name='rating',
            field=models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')], null=True),
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='char_class',
        ),
        migrations.AddField(
            model_name='characterclass',
            name='char_class',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.RemoveField(
            model_name='component',
            name='components',
        ),
        migrations.AddField(
            model_name='component',
            name='components',
            field=models.CharField(choices=[('V', 'Verbal'), ('S', 'Somatic'), ('M', 'Material')], default='None', max_length=20),
        ),
        migrations.RemoveField(
            model_name='damagetype',
            name='damage_type',
        ),
        migrations.AddField(
            model_name='damagetype',
            name='damage_type',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.RemoveField(
            model_name='effect',
            name='effects',
        ),
        migrations.AddField(
            model_name='effect',
            name='effects',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
