# Generated by Django 4.0.3 on 2022-04-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_spell_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 'No Rating'), (1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')], null=True),
        ),
    ]
