# Generated by Django 4.0.3 on 2022-04-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_spell_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='att_save',
        ),
        migrations.AddField(
            model_name='spell',
            name='attack',
            field=models.CharField(choices=[('M', 'Melee Spell Attack'), ('R', 'Ranged Spell Attack')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='spell',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='save',
            field=models.CharField(choices=[('M', 'Melee Spell Attack'), ('R', 'Ranged Spell Attack')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='spell',
            name='area',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.CharField(max_length=20),
        ),
    ]
