# Generated by Django 4.0.3 on 2022-04-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_spell_att_save_spell_attack_spell_favorite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='favorite',
        ),
    ]
