# Generated by Django 4.0.3 on 2022-04-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_spell_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='area',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='range',
        ),
    ]
