# Generated by Django 4.0.3 on 2022-04-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_spell_area_remove_spell_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='area',
            field=models.CharField(default='Target', max_length=30),
        ),
        migrations.AddField(
            model_name='spell',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='range',
            field=models.CharField(default='Touch', max_length=20),
        ),
    ]
