# Generated by Django 4.0.3 on 2022-04-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_spell_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='area',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='area_shape',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='range',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='save',
        ),
    ]
