# Generated by Django 4.0.3 on 2022-04-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_spell_area_remove_spell_area_shape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
