# Generated by Django 4.0.3 on 2022-04-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_spell_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='save',
        ),
    ]
