# Generated by Django 4.0.3 on 2022-04-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_spell_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='attack',
            field=models.CharField(choices=[('M', 'Melee Spell Attack'), ('R', 'Ranged Spell Attack')], default='None', max_length=30),
        ),
    ]
