# Generated by Django 4.0.3 on 2022-04-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_spell_attack'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='area',
            field=models.CharField(default='Target', max_length=30),
        ),
        migrations.AddField(
            model_name='spell',
            name='area_shape',
            field=models.CharField(choices=[('N', 'None'), ('R', 'Radius'), ('C', 'Cube'), ('S', 'Sphere'), ('Y', 'Cylinder')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='spell',
            name='range',
            field=models.CharField(default='Touch', max_length=20),
        ),
    ]
