# Generated by Django 4.0.3 on 2022-04-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_spell_saving_throw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school',
            new_name='name',
        ),
    ]
