# Generated by Django 4.0.3 on 2022-04-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_school_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='area_shape',
            field=models.CharField(choices=[('N', 'None'), ('R', 'Radius'), ('C', 'Cube'), ('S', 'Sphere'), ('Y', 'Cylinder'), ('O', 'Cone')], default='None', max_length=20),
        ),
    ]
