# Generated by Django 4.0.3 on 2022-04-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_spell_attack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='upcasting',
            field=models.TextField(default='No additional effects when upcast.', max_length=1000),
        ),
    ]
