# Generated by Django 4.0.3 on 2022-04-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_spell_upcasting'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='ritual',
            field=models.BooleanField(default=False),
        ),
    ]
