# Generated by Django 4.0.3 on 2022-04-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_spell_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
