# Generated by Django 4.0.3 on 2022-04-05 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0039_alter_spell_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='user',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('created_spells', models.ManyToManyField(blank=True, related_name='creator', to='app.spell')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='app.spell')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
