# Generated by Django 4.0.3 on 2022-04-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_spell_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/media/default.png', upload_to='profile_images'),
        ),
    ]
