# Generated by Django 4.0.3 on 2022-04-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_rating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='materials',
            field=models.TextField(default='None', max_length=500),
        ),
    ]
