# Generated by Django 4.0.3 on 2022-04-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_profile_avatar_alter_spell_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='materials',
            field=models.TextField(default='None', max_length=500),
        ),
    ]
